controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

telegram_bundle:
    resource: '@TelegramBundle/config/routes.yaml'
    prefix: /telegram
    name_prefix: telegram